# Generated by Django 5.0.3 on 2024-04-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
