# Generated by Django 5.0.3 on 2024-03-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notesManage", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="notes",
            name="notes",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
